### PR TITLE
Fix time interval math when working with query time zones

### LINKED ISSUE #2564: Timezones with DST + filter expressions return incomplete data
### What happens?

The issue with DST timezones occurs for many filter expressions: 
- months
- last months
- weeks
- last weeks
- ago ...
- from now ...
and probably more.

I checked DuckDB, MySQL and PostgresSQL.

Europe/Dublin - 3 months in results

```
run: flights -> {
  group_by: arr_time_month is arr_time.month
  where: arr_time.month ~ f`last 242 months`
  order_by: arr_time_month asc
  timezone: 'Europe/Dublin'
}
```

```sql
SELECT 
    (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP as "arr_time_month"
FROM db1.flights as base
WHERE (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP
    >= (DATE_TRUNC('month', ((LOCALTIMESTAMP)::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP - INTERVAL (242) month 
  AND (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP < (DATE_TRUNC('month', ((LOCALTIMESTAMP)::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP
GROUP BY 1
ORDER BY 1 asc NULLS LAST
```

```json
[
  {
    "arr_time_month": "2005-09-30T23:00:00.000Z"
  },
  {
    "arr_time_month": "2005-11-01T00:00:00.000Z"
  },
  {
    "arr_time_month": "2005-12-01T00:00:00.000Z"
  }
]
```

UTC - 4 months in results

```
run: flights -> {
  group_by: arr_time_month is arr_time.month
  where: arr_time.month ~ f`last 242 months`
  order_by: arr_time_month asc
  timezone: 'UTC'
}
```

```sql
SELECT 
   (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'UTC')) 
      AT TIME ZONE 'UTC'
    )::TIMESTAMP as "arr_time_month"
FROM db1.flights as base
WHERE (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'UTC')) 
      AT TIME ZONE 'UTC'
    )::TIMESTAMP >= (DATE_TRUNC('month', ((LOCALTIMESTAMP)::TIMESTAMPTZ 
      AT TIME ZONE 'UTC')) 
      AT TIME ZONE 'UTC'
    )::TIMESTAMP - INTERVAL (242) month AND (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'UTC')) 
      AT TIME ZONE 'UTC'
    )::TIMESTAMP < (DATE_TRUNC('month', ((LOCALTIMESTAMP)::TIMESTAMPTZ 
      AT TIME ZONE 'UTC')) 
      AT TIME ZONE 'UTC'
    )::TIMESTAMP
GROUP BY 1
ORDER BY 1 asc NULLS LAST
```

```json
[
  {
    "arr_time_month": "2005-09-01T00:00:00.000Z"
  },
  {
    "arr_time_month": "2005-10-01T00:00:00.000Z"
  },
  {
    "arr_time_month": "2005-11-01T00:00:00.000Z"
  },
  {
    "arr_time_month": "2005-12-01T00:00:00.000Z"
  }
]
```

If Malloy does not use the second conversion “AT TIME ZONE”, the query returns correct results:

```sql
SELECT 
    (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      -- AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP as "arr_time_month"
FROM db1.flights as base
WHERE (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      -- AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP
    >= (DATE_TRUNC('month', ((LOCALTIMESTAMP)::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      -- AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP - INTERVAL (242) month 
  AND (DATE_TRUNC('month', ((base."arr_time")::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      -- AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP < (DATE_TRUNC('month', ((LOCALTIMESTAMP)::TIMESTAMPTZ 
      AT TIME ZONE 'Europe/Dublin')) 
      -- AT TIME ZONE 'Europe/Dublin'
    )::TIMESTAMP
GROUP BY 1
ORDER BY 1 asc NULLS LAST
```

arr_time_month
2005-09-01 00:00:00
2005-10-01 00:00:00
2005-11-01 00:00:00
2005-12-01 00:00:00

### To Reproduce

-

### OS:

macOS

### Malloy Client:

local VSCode

### Malloy Client Version:

 0.3.1762565760

### Database Connection:

MotherDuck (DuckDB)

### PR DESCRIPTION
**Pull request by mtoy-googly-moogly**
## Problem
Calendar-based interval operations (months, quarters, years, days) on timestamps were not timezone-aware. For example, `@2024-11-01[Europe/Dublin] - 5 months` incorrectly computed to the wrong civil time because Dublin's UTC offset differs between November (UTC+0) and June (UTC+1).

## Solution
Implemented a helper method architecture where the base `Dialect` class orchestrates civil time computation, and each dialect implements four abstract methods:

- **`sqlConvertToCivilTime(expr, timezone)`** - Convert UTC timestamp to civil (local) time in the specified timezone
- **`sqlConvertFromCivilTime(expr, timezone)`** - Convert civil time back to UTC timestamp
- **`sqlTruncate(expr, unit, typeDef, inCivilTime, timezone)`** - Truncate to a time unit (day, week, month, etc.)
- **`sqlOffsetTime(expr, op, magnitude, unit, typeDef, inCivilTime, timezone)`** - Add/subtract time intervals

> Dialects can optionally override **`needsCivilTimeComputation()`** to customize which operations require civil time conversion (BigQuery has its own implementation; others use the default).

The base `sqlTruncAndOffset` method uses these helpers to automatically determines when calendar operations need civil time conversion (crossing DST boundaries) and orchestrates the conversion → operation → conversion flow.

The dialect methods `sqlTruncExpr` and `sqlAlterTimeExpr` are removed and all code paths flow through sqlTruncOffset.

I believe this will fix #2564

### CODE REVIEW

File: packages/malloy/src/dialect/dialect.ts [hunk 1]
```diff
@@ -276,13 +276,214 @@ export abstract class Dialect {
...
+    const needed =
+      TD.isTimestamp(typeDef) &&
+      (isCalendarTruncate || isCalendarOffset) &&
+      tz !== undefined;
+
+    return {needed, tz};
+  }
+
+  /**
+   * Unified function for truncation and/or offset operations.
```
Comment (mtoy-googly-moogly) [inline packages/malloy/src/dialect/dialect.ts]: mention that the intention is that this NOT be over-ridden and the dialect quirks should be in the helper functions.
